### ISSUE TITLE
Extract Lat/Lon (and other metadata) from image EXIF

### ISSUE THREAD

**Issue by dingaaling** [alan-turing-institute/plankton-dsg-challenge#10]
https://github.com/alan-turing-institute/plankton-dsg-challenge/tree/dsg2021/data/processed/exif

**Comment by ghost** [comment]
The exif.csv file contains all the available EXIF data including GPS. You can find it at https://github.com/alan-turing-institute/plankton-dsg-challenge/tree/dsg2021/data/processed/exif
