### ISSUE TITLE
Spatial analysis of data - are the species clustered?

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/plankton-dsg-challenge#14]

**Comment by CharlieHewitt1** [comment]
kernel density estimation showed that at the first stage of classification (plankton vs. detritus) that there are two distinct & separate areas of clustering of the two types of variables - maps are provided in the hackMD and overleaf report.

**Comment by ghost** [comment]
Nice work by @CharlieHewitt1 and @sarigiering
